=== AniketosEU/Security-Monitoring-and-Notification/aniketos-policymonitoring/eu.aniketos.spmm.impl/rsc/xsd_aniketos.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="typeType">
			<xs:restriction base="xs:string">
				<xs:enumeration value="int"/>
				<xs:enumeration value="bool"/>
				<xs:enumeration value="string"/>
			</xs:restriction>
</xs:simpleType> 


<xs:complexType name="invocationType">
	<xs:sequence>
		<xs:element name="identifier" type="xs:string" minOccurs="1" maxOccurs="2"/>
		<xs:element name="argument" minOccurs="0" maxOccurs="unbounded">
		  <xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:group name="AexpType">
	<xs:choice>
		<xs:element name="sum">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="dif">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="mul">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="mod">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="iconst" type="xs:integer"/>
		<xs:element name="i_identifier" type="xs:string"/>
	</xs:choice>
</xs:group> 

<xs:group name="expType">
	<xs:choice>
		<xs:group ref="AexpType"/>
		<xs:group ref="BexpType"/>
		<xs:group ref="SexpType"/>
		<xs:element name="invocation" type="invocationType"/>
	</xs:choice>
</xs:group> 




<xs:group name="BexpType">
	<xs:choice>
		<xs:element name="or">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="and">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="not">
			<xs:complexType>
				<xs:group ref="expType"/>
			</xs:complexType>
		</xs:element>
		<xs:element name="bconst" type="xs:boolean"/>
		<xs:element name="b_identifier" type="xs:string"/>
		<xs:element name="morethan">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="lessthan">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="i_equal">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="AexpType"/>
					<xs:group ref="AexpType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="b_equal">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="BexpType"/>
					<xs:group ref="BexpType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="s_equal">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="SexpType"/>
					<xs:group ref="SexpType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="morequalthan">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="lessequalthan">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="notequal">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
	</xs:choice>
</xs:group> 

<xs:group name="SexpType">
	<xs:choice>
		<xs:element name="append">
			<xs:complexType>
				<xs:sequence>
					<xs:group ref="expType"/>
					<xs:group ref="expType"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		<xs:element name="sconst" type="xs:string"/>
		<xs:element name="s_identifier" type="xs:string"/>
	</xs:choice>
</xs:group> 



<xs:complexType name="whenType">
	<xs:sequence>
		<xs:element name="identifier" type="xs:string"/>
		<xs:element name="parameter" type="parameterType" minOccurs="0" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType> 

<xs:complexType name="afterType">
<xs:complexContent>
	<xs:extension base="whenType">
	<xs:sequence>
	<xs:element name="return" type="parameterType" minOccurs="0"/>
	</xs:sequence>
	</xs:extension>
	</xs:complexContent>
</xs:complexType> 

<xs:complexType name="parameterType">
	<xs:sequence>
		<xs:element name="type" type="typeType"/>
		<xs:element name="identifier" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="performType">
	<xs:sequence>
		<xs:element name="reaction" type="reactionType" maxOccurs="unbounded"/>
		<xs:element name="else" type="updateType" minOccurs="0"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="reactionType">
	<xs:sequence>
	<xs:element name="guard">
	<xs:complexType>
    <xs:sequence> 
	    <xs:group ref="expType"/>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
		
		<xs:element name="update" type="updateType"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="updateType">
<xs:sequence>
<xs:element name="assign" type="assignType" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>

<xs:complexType name="assignType">
	<xs:sequence>
		<xs:element name="identifier" type="xs:string"/>
		<xs:element name="value">
        <xs:complexType>
				  <xs:sequence>
					  <xs:group ref="expType"/>
				  </xs:sequence>
			  </xs:complexType>
			</xs:element>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="declType">
	<xs:sequence>
		<xs:element name="type" type="typeType"/>
		<xs:element name="identifier" type="xs:string"/>
		<xs:element name="value">
		<xs:complexType>
				  <xs:sequence>
					  <xs:group ref="expType"/>
				  </xs:sequence>
			  </xs:complexType>
			</xs:element>
	</xs:sequence>
</xs:complexType> 

<xs:complexType name="stateType">
  <xs:sequence>
	<xs:element name="declaration" type="declType" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType> 

<xs:complexType name="ruleType">
	<xs:sequence>
		<xs:choice>
			<xs:element name="before" type="whenType"/>
			<xs:element name="after" type="afterType"/>
			<xs:element name="exceptional" type="whenType"/>
		</xs:choice>
		<xs:element name="perform" type="performType"/>
	</xs:sequence>
</xs:complexType> 

<xs:element name="specification">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="maxint" type="xs:integer" minOccurs="0"/>
      <xs:element name="maxlen" type="xs:integer" minOccurs="0"/>
      <xs:element name="scope">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="session"/>
				<xs:enumeration value="multisession"/>
				<xs:enumeration value="global"/>
			</xs:restriction>
		</xs:simpleType>
	  </xs:element> 
      <xs:element name="securitystate" type="stateType" minOccurs="0"/>
      <xs:element name="rule" type="ruleType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:string"/> 
  </xs:complexType>
</xs:element>


</xs:schema>

=== AniketosEU/Security-Monitoring-and-Notification/aniketos-policymonitoring/eu.aniketos.spmm.impl/rsc/Trustworthiness.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification id="Rule8"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="xsd_aniketos.xsd">
<maxint>32000</maxint>
<maxlen>3000</maxlen>
   <scope>session</scope>

  <securitystate>
    <declaration>
      <type>int</type>
      <i_identifier>trustworthiness_threshold</i_identifier>
      <value>
        <iconst>7</iconst>
      </value>
    </declaration>
  </securitystate>


  <rule>
    <before>
      <identifier>invokeService</identifier>
      <parameter>
        <type>string</type>
        <identifier>s</identifier>
      </parameter>
    </before>
    <perform>
      <reaction>
        <guard>
          <morethan>
               <invocation>
                  <identifier>evaluateTrustworthiness</identifier>
                  <argument>
        			  <s_identifier>s</s_identifier>
                  </argument>
               </invocation>
               <i_identifier>trustworthiness_threshold</i_identifier>
	  </morethan>
        </guard>
        <update/>
      </reaction>
    </perform>
  </rule>

</specification>

=== AniketosEU/Security-Monitoring-and-Notification/aniketos-policymonitoring/eu.aniketos.spmm.impl/rsc/Confidentiality_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification id="Confidentiality_new" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aniketos.xsd"><maxint>32000</maxint><maxlen>1000</maxlen><scope>session</scope><securitystate><declaration><type>string</type><identifier>Service</identifier><value><sconst>Send_Document</sconst></value></declaration><declaration><type>string</type><identifier>inputSuite</identifier><value><sconst>Basic256Sha256Rsa15</sconst></value></declaration><declaration><type>string</type><identifier>inputSchema</identifier><value><sconst>symmetric</sconst></value></declaration><declaration><type>string</type><identifier>inputAlgorithm</identifier><value><sconst>AES</sconst></value></declaration><declaration><type>int</type><identifier>inputKeyLength</identifier><value><iconst>256</iconst></value></declaration><declaration><type>string</type><identifier>outputSuite</identifier><value><sconst>Basic256Sha256Rsa15</sconst></value></declaration><declaration><type>string</type><identifier>outputSchema</identifier><value><sconst>symmetric</sconst></value></declaration><declaration><type>string</type><identifier>outputAlgorithm</identifier><value><sconst>AES</sconst></value></declaration><declaration><type>int</type><identifier>outputKeyLength</identifier><value><iconst>256</iconst></value></declaration></securitystate><rule><before><identifier>activity.end</identifier><parameter><type>string</type><identifier>id</identifier></parameter><parameter><type>string</type><identifier>type</identifier></parameter><parameter><type>int</type><identifier>time</identifier></parameter><parameter><type>int</type><identifier>date</identifier></parameter><parameter><type>string</type><identifier>exec</identifier></parameter><parameter><type>string</type><identifier>Output</identifier></parameter></before><perform><reaction><guard><and><s_equal><s_identifier>id</s_identifier><s_identifier>Service</s_identifier></s_equal><invocation><b_identifier>java.prova.ConfidentialityCheck</b_identifier><b_identifier>result</b_identifier><argument><s_identifier>Service</s_identifier></argument><argument><s_identifier>inputSuite</s_identifier></argument><argument><s_identifier>inputSchema</s_identifier></argument><argument><s_identifier>inputAlgorithm</s_identifier></argument><argument><i_identifier>inputKeyLength</i_identifier></argument><argument><s_identifier>outputSuite</s_identifier></argument><argument><s_identifier>outputSchema</s_identifier></argument><argument><s_identifier>outputAlgorithm</s_identifier></argument><argument><i_identifier>outputKeyLength</i_identifier></argument></invocation></and></guard><update /></reaction></perform></rule></specification>

=== AniketosEU/Security-Monitoring-and-Notification/aniketos-policymonitoring/eu.aniketos.spmm.impl/rsc/specification.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification id="eu.aniketos.conspec.policy.example"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="xsd_aniketos.xsd">
  <maxint> 1024 </maxint>
  <maxlen> 64 </maxlen>
  <scope>session</scope>
  <securitystate>
    <declaration>
      <type>int</type>
      <identifier>buffer_size</identifier>
      <value>
        <iconst>0</iconst>
      </value>
    </declaration>
    <declaration>
      <type>string</type>
      <identifier>last</identifier>
      <value>
        <sconst/>
      </value>
    </declaration>
  </securitystate>
  <rule>
    <before>
      <identifier>java.io.OutputStream.write</identifier>
      <parameter>
        <type>string</type>
        <identifier>b</identifier>
      </parameter>
      <parameter>
        <type>int</type>
        <identifier>off</identifier>
      </parameter>
      <parameter>
        <type>int</type>
        <identifier>len</identifier>
      </parameter>
    </before>
    <perform>
      <reaction>
        <guard>
          <morethan>
            <iconst>512</iconst>
            <i_identifier>buffer_size</i_identifier>
          </morethan>
        </guard>
        <update>
          <assign>
            <identifier>buffer_size</identifier>
            <value>
              <sum>
                <i_identifier>buffer_size</i_identifier>
                <i_identifier>len</i_identifier>
              </sum>
            </value>
          </assign>
        </update>
      </reaction>
    </perform>
  </rule>
  <rule>
    <after>
      <identifier>java.io.OutputStream.flush</identifier>
      <return>
        <type>int</type>
        <identifier>len</identifier>
      </return>
    </after>
    <perform>
      <reaction>
        <guard>
          <bconst>true</bconst>
        </guard>
        <update>
          <assign>
            <identifier>buffer_size</identifier>
            <value>
              <dif>
                <i_identifier>buffer_size</i_identifier>
                <i_identifier>len</i_identifier>
              </dif>
            </value>
          </assign>
        </update>
      </reaction>
    </perform>
  </rule>
  <rule>
    <exceptional>
      <identifier>java.io.OutputStream.flush</identifier>
    </exceptional>
    <perform>
      <reaction>
        <guard>
          <bconst>true</bconst>
        </guard>
        <update/>
      </reaction>
    </perform>
  </rule>
  <rule>
    <before>
      <identifier>java.net.Socket.&lt;init&gt;</identifier>
      <parameter>
        <type>string</type>
        <identifier>host</identifier>
      </parameter>
      <parameter>
        <type>int</type>
        <identifier>port</identifier>
      </parameter>
    </before>
    <perform>
      <reaction>
        <guard>
          <invocation>
            <identifier>java.lang.String.equals</identifier>
            <identifier>host</identifier>
            <argument>
              <s_identifier>last</s_identifier>
            </argument>
          </invocation>
        </guard>
        <update/>
      </reaction>
      <reaction>
        <guard>
          <invocation>
            <identifier>java.lang.String.equals</identifier>
            <identifier>last</identifier>
            <argument>
              <sconst/>
            </argument>
          </invocation>
        </guard>
        <update>
          <assign>
            <identifier>last</identifier>
            <value>
              <s_identifier>host</s_identifier>
            </value>
          </assign>
        </update>
      </reaction>
    </perform>
  </rule>
</specification>

=== AniketosEU/Security-Monitoring-and-Notification/aniketos-policymonitoring/eu.aniketos.spmm.impl/rsc/SoD_Goal.xml
<?xml version="1.0" encoding="UTF-8"?>
<specification id="SoD_Goal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aniketos.xsd">
  <maxint>32000</maxint>
  <maxlen>1000</maxlen>
  <scope>session</scope>
  <securitystate>
    <declaration>
      <type>string</type>
      <identifier>executor</identifier>
      <value>
        <sconst>_</sconst>
      </value>
    </declaration>
    <declaration>
      <type>string</type>
      <identifier>guardedTask1</identifier>
      <value>
        <sconst>Map</sconst>
      </value>
    </declaration>
    <declaration>
      <type>string</type>
      <identifier>guardedTask2</identifier>
      <value>
        <sconst>PointOfInterest</sconst>
      </value>
    </declaration>
  </securitystate>
  <rule>
    <before>
      <identifier>activity.start</identifier>
      <parameter>
        <type>string</type>
        <identifier>id</identifier>
      </parameter>
      <parameter>
        <type>string</type>
        <identifier>type</identifier>
      </parameter>
      <parameter>
        <type>string</type>
        <identifier>time</identifier>
      </parameter>
      <parameter>
        <type>string</type>
        <identifier>date</identifier>
      </parameter>
      <parameter>
        <type>string</type>
        <identifier>provider</identifier>
      </parameter>
    </before>
    <perform>
      <reaction>
        <guard>
          <and>
            <or>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask1</s_identifier>
              </s_equal>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask2</s_identifier>
              </s_equal>
            </or>
            <s_equal>
              <s_identifier>executor</s_identifier>
              <sconst>_</sconst>
            </s_equal>
          </and>
        </guard>
        <update>
          <assign>
            <s_identifier>executor</s_identifier>
            <value>
              <s_identifier>provider</s_identifier>
            </value>
          </assign>
        </update>
      </reaction>
      <reaction>
        <guard>
          <and>
            <or>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask1</s_identifier>
              </s_equal>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask2</s_identifier>
              </s_equal>
            </or>
            <and>
              <not>
                <s_equal>
                  <s_identifier>executor</s_identifier>
                  <sconst>_</sconst>
                </s_equal>
              </not>
              <not>
                <s_equal>
                  <s_identifier>provider</s_identifier>
                  <s_identifier>executor</s_identifier>
                </s_equal>
              </not>
            </and>
          </and>
        </guard>
        <update />
      </reaction>
      <reaction>
        <guard>
          <and>
            <not>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask1</s_identifier>
              </s_equal>
            </not>
            <not>
              <s_equal>
                <s_identifier>id</s_identifier>
                <s_identifier>guardedTask2</s_identifier>
              </s_equal>
            </not>
          </and>
        </guard>
        <update />
      </reaction>
    </perform>
  </rule>
</specification>
